name: Create Version File

on: [push]

jobs:
  create-version-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Create v.txt with commit hash
      run: |
        echo "${{ github.sha }}" > v.txt
    
    - name: Commit and push v.txt
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add v.txt
        git commit -m "Add v.txt with commit hash" || exit 0
        git push